# Generated by Django 4.0.1 on 2022-01-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_skill_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-rating'], 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(help_text='Enter a brief description of the project'),
        ),
    ]
