# Generated by Django 4.0.1 on 2022-01-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_skill_options_alter_contact_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='Enter the link to the project', null=True),
        ),
    ]
